### PR TITLE
Simplified AbstractJsonSerializer and applied refactoring to all exis…

### PR DESCRIPTION
**Pull request by chutchinson**
This is a breaking change.

Please review the changes made to the existing serializers in respect to AbstractJsonSerializer. This change simplifies the JSON serialization mechanism.

There have also been changes to the following assets:
- Board
- SpecialMove
- Project

In the future, please ensure all assets implement Asset or inherit from AbstractAsset. I will mark BasicType as deprecated soon. 

Do not think of assets as a direct representation of the contents of their serialized form. Asset types will be used directly in the engine and should represent their concepts and not how they will be serialized. It's the AssetSerializer's job to do care about data structure, data types, etc. during serialization.

Do not use strings to represent linked assets. Always use an AssetDescriptor. See the JsonSpecialMoveSerializer and SpecialMove for a concrete example.

### CODE REVIEW

**Comment by chutchinson** [comment]
Naturally these changes break editor code. I will be resolving this discrepancy soon.

**Comment by mariobadr** [comment]
I would mark BasicType as deprecated with this pull request. 

I noticed all the board loading code is being removed - is it no longer possible to load the old board format with this change?

**Comment by chutchinson** [comment]
No. The binary serialization should be moved to a serialzer.

**Comment by goblinJoel** [comment]
So... did you move it or just delete it? ;P

**Comment by chutchinson** [comment]
I deleted it but since we're using version control whoever reimplements the
binary serializer can reference a prior commit.

**Comment by mariobadr** [comment]
I think we should try to incorporate the deleted code into a binary serializer for this pull request, though I'm not sure how much work this would entail. If people disagree then I think we can go ahead and merge this.

**Comment by goblinJoel** [comment]
I agree with Marz. I'm not fond of features disappearing because "they were in the wrong place" (according to a standard implemented after the fact), with the expectation that someone else will figure out what happened, go through the commit history, and then move stuff to where it should have been.

BUT, I like the changes to the JSON serializer and am happy with the commits. (I just finished looking through it. For some reason, I'd found the JSON stringer and not noticed the object.put() before. This method is simpler than what I'd been doing, and it still allows inheritance.) Good work, @chutchinson .

I think we could merge after the binary serializers are moved to where they should be.

**Comment by chutchinson** [comment]
We can hold off until we re-implement the binary serialization for the Board / Project assets. I will make that a personal priority to expedite this pull request.

**Comment by goblinJoel** [comment]
Awesome. You the bomb.

**Comment by chutchinson** [comment]
I'll keep making commits to this branch as I re-implement the serialization. I think a better approach is to fix discrepancies created by this branch in the editor project before closing the PR.

I will probably be making significant changes to the Board class to move its implementation away from mapping so closely to the original binary format.

**Comment by swordmaster2k** [comment]
Personally I don't think we should be prioritizing legacy serializers. I can count the people who are going to directly upgrade projects and assets from 3.x to 4.x on one hand.

As Chris pointed out there are enhancements that could be made to the Board class if the mapping to the original binary format was not so rigid.

If you need help with integrating these changes into the editor let me know, I prefer to keep my working branches up to date with the core.

**Comment by goblinJoel** [comment]
I don't think we should prioritize _adding_ legacy serializers over modern ones, but the issue here is that we had them, and I'd rather not regress as we make otherwise-helpful rearrangements.

**Comment by goblinJoel** [comment]
I think Chris just meant that he's prioritizing moving that functionality rather than deleting it, for this specific pull request, so that Marz and I won't be grumpy about merging it in. ;)

**Comment by mariobadr** [comment]
I was more hoping to keep it so that we could still load some boards for the engine until the new file format is complete.

**Comment by goblinJoel** [comment]
Has there been any movement on this? Should I start moving the binary serializers to where they should be, or has that already been done, but not pushed?

**Comment by goblinJoel** [comment]
Looking at the commits, it looks like Board, Project, and SpecialMove had their legacy serializers removed, but Board's has been reimplemented, but not tested.

Would it make sense for me to follow the legacy Board serializer's example to restore Project and SpecialMove legacy serializers, or are those already done somewhere, or is it best to let Euix handle it to avoid confusion?

**Comment by chutchinson** [comment]
Focus on other binary serializers. There's still assets left that have open/save methods that need to be moved. Also consider modifying the implementation of any existing assets to remove any extraneous fields or variables that were being used for I/O. The only fields, methods, and variables appropriate for assets are those used by the engine for gameplay. 

I am heavily refactoring Board, SpecialMove, StatusEffect, and Project to reflect that point of view, and that's the reason there hasn't been a lot of activity. It's not a huge amount of work but it's enough that I've had to chip away at it.

**Comment by goblinJoel** [comment]
About that. I noticed status effects' fields had mostly been condensed into a generic list of "attributes". But those were certainly things the engine would have used. I assume the idea there is the basically let you add the equivalent of tags to your status effects, then let it be up to your game's programming how those are interpreted? But it also looks like the StatusEffectAttribute class doesn't exist yet. Anyway, it seems like a good idea, but I do wonder how much you're trying to accomplish all on this serialization update branch.

I asked about the Board, SpecialMove, and Project binary serializers only because I was looking to get this pull request wrapped up and merged so we can move on and code against its changes, and those are the ones that I noticed got deleted. Anyway, thanks for working on this, and do let us know as soon as the regression (binary serialization disappearing) is fixed. :)

Also, maybe we should communicate more about changes we want to make before we make them. I think some of us are looking to recreate TK3 functionality, but with a better basis for expansion, while others are wanting to change what the pieces of the Toolkit do. Not to give you a hard time, but it can get a little confusing to think, "Ok, we've got this editor ported to the new codebase!" only to see, "Actually, I decided the Toolkit should work differently." I tend to feel like adding new features and redoing user-facing features can wait until we've gotten back to where we were and can get community feedback on what comes next.

None of this is to rag on you for having new (probably better) ideas, of course! You've done a tremendous amount of refactoring for the toolkit, and I have confidence those changes are for the best long-term. I just want to make sure we're all on the same page for what the initial release is supposed to be.

**Comment by goblinJoel** [comment]
Sorry for a zillion posts.

Refactored enemy and player deserializers to new LegacyFooSerializer classes per Euix's suggestion (Chris is Euix, right?). Apologies if this causes more conflicts with the character editor branch. I did not move the save methods out to the serializer yet, as I'm unfamiliar with binary IO and will wait for another one to be implemented as an example.

I did change the types of a few vars from byte to boolean, since the latter is what they are logically. The binary serializer (should) take care of converting instead of the asset class. Also changed a couple assets to extend AbstractAsset instead of BasicType.

**Comment by chutchinson** [comment]
I have no problem with discussing significant changes, but I'm not sure how to go about doing that. My position to this stage has been to provide the foundation for the engine. The foundation is critical to the construction and performance of the engine, and I feel like essentially porting the existing architecture of the engine and all of the flaws and mistakes is not a good idea.

I want to strive for backwards compatibility to support historical projects, the basic problem for me is that the underlying plumbing is paramount. It is not practical to shotgun blast the foundation into existence just for the sake of progress, only to come back down the road and refactor the design later. We should get it close to right the first time around.

I will make an effort to post on the discussion board when I want to introduce architectural refactoring or other significant framework changes.

Don't be too afraid of the legacy serializers. As long as you end up reading or writing with the ByteBuffer supplied by the asset framework with NIO you're doing the right thing. Looking at the legacy board serializer is a good example even though it's not finished. Writing is a little harder than reading because you don't have a fixed length buffer so you'll need to combine multiple smaller buffers and some bounds checking.

**Comment by goblinJoel** [comment]
Your point is well taken. It doesn't make sense to blindly copy flaws over. Mostly, I'm talking about interface stuff, in the sense of, "You make a board in the editor, which you walk around on in the game. It has areas you can define where programs will trigger, etc." Equivalence in what pieces a person makes and what they mean for the game. Having similar features, even if the backend wiring is different. And I don't think we've necessarily moved away from that; I might have gotten the wrong impression of the scope of what you're looking to change right away.

Anyway, as you can see, I did a couple binary deserializers, though I haven't tried any serializing yet.

**Comment by goblinJoel** [comment]
Added untested legacy item deserialization, refactored a few things there (see commit 5d05b56)

**Comment by goblinJoel** [comment]
First attempt at writing a legacy serializer. I was going to wait until I saw an example, but everyone's disappeared. So... I hope I did it right? I noticed byte buffers are created by default with big-endian order, but our legacy deserializers expect little-endian. Does that mean I need to do some manual swapping around with the bytes I get from the UTF-8 strings?

For that matter, does legacy even support UTF-8, or does it need ASCII?

**Comment by mariobadr** [comment]
This is the problem when you have volunteers - life gets really busy unfortunately.

I see no new commits since December - have you pushed?

**Comment by mariobadr** [comment]
Never mind I see it now. It seems to make sense to me, though I didn't write the asset repo stuff.

As a future note, it would be nice if priority() actually returned some form of priority (enum?) instead of an integer.

**Comment by chutchinson** [comment]
For this specific case I disagree with priority being an enumeration. The
goal of that field is to provide granular control over asset load order.
It's so you can force the pipeline to use a particular serializer if there
is more than one for an asset. I think an enumerable priority is more
appropriate for scheduled types / data.

**Comment by chutchinson** [comment]
@goblinJoel ByteBuffer#order(...) specifies the byte-order that all following get/put calls will use for binary access. To my knowledge all of the legacy formats assume ASCII character encoding. Also for your reference, UTF-8 is a single byte encoding and by extension byte order is not applicable. The version of **LegacyBoardSerializer** in this branch shows an example of using a byte buffer and specifying little-endian byte order.

http://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html

**Comment by goblinJoel** [comment]
Yeah, I saw how to specify it, but it appeared that didn't alter existing
data, so it didn't look like it would do any good to set that flag if the
string bytes were being created separately. Also, I apparently didn't
understand byte ordering, because I thought each byte was affected. (I was
under the impression byte order determined the place value of the
individual bits in a byte.). So it's good that it doesn't matter on UTF-8,
though it sounds like for legacy serializers we'll have to fix my UTF-8 to
ASCII.

On Mon, Mar 7, 2016 at 3:00 PM, Chris Hutchinson notifications@github.com
wrote:

> @goblinJoel https://github.com/goblinJoel ByteBuffer#order(...)
> specifies the byte-order that all following get/put calls will use for
> binary access. To my knowledge all of the legacy formats assume ASCII
> character encoding. Also for your reference, UTF-8 is a single byte
> encoding and by extension byte order is not applicable. The version of
> _LegacyBoardSerializer_ in this branch shows an example of using a byte
> buffer and specifying little-endian byte order.
> 
> http://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rpgtoolkit/core/pull/7#issuecomment-193424806.

## 

Yésús yavayva, "On a megvil na a dashú na a sfaivli. Shosho ymwavran a
Fadrayado yapa onkin." -Yohanan 14:6

**Comment by goblinJoel** [comment]
Ok then, switched legacy formats to ascii strings and put the utf-8 one back in the abstract json serializer

**Comment by goblinJoel** [comment]
I'm _pretty sure_ I fixed an off-by-one bug in legacy animated tile loading that would have skipped the last animation frame. Unless the count integer is actually, intentionally, one larger than the number of frames. (In which case, the old save code would have been wrong by writing one _less_ than the number of frames.) Do we have access to a schema for these old formats? Some of them were on someone's github project at some point earlier.

Added a serialize method for legacy animated tiles based on one that had been removed.

**Comment by chutchinson** [comment]
You'll need to look at the Visual Basic modules in the original Source
Forge CVS to derive the file format schemas. There are a few similar bugs
as the one you've mentioned because the VB code iterated from 0 to UBound
which is a function that returns the upper bound of a fixed length array. A
lot of the arrays are also allocated with one extra element so that's why
there appears to be a null byte wherever strings are stored in sequence.
The code is writing an empty null terminated string because the editor only
accesses and stores UBOUND - 1.

**Comment by goblinJoel** [comment]
I'm looking to wrap up the legacy serializers so we can merge this. @chutchinson , how close are the Board, SpecialMove, Project, and StatusEffect legacy serializers to being done? You said earlier that I should focus on the other ones; is that still true?

EDIT: I looked through the pull request again, and it looks like the following were removed (checked ones have been restored since):
- [x] Background save/load
- [ ] Board save/load
- [x] Enemy load
- [x] Player load
- [ ] Project save/load
- [ ] Special Move save/load
- [ ] Status Effect save/load

**Comment by goblinJoel** [comment]
I'm worried I'm doing a couple things wrong:
1. chutchinson mentioned some weirdness with reading/writing arrays of things with the legacy formats. This probably means there are bugs in my serializers/deserializers or inconsistencies between them.
2. I think ByteBufferHelper.getBuffer(String s) doesn't null-terminate the strings, but that is expected when we read them with the same's getTerminatedString(ByteBuffer buffer). I'm guessing I need to always insert a \0 char there, and I've added that in my next commit. Does that sound right?
3. There are tons of cases where we're using ints and longs where legacy used shorts and ints. This brings up hypothetical casting problems when we save legacy stuff, which could result in incorrect data or, in the case of a list having more members than can fit in a short, a corrupted file. (If the list length we write has been truncated on-cast, but we still write all members of the list, the file will not read correctly on the way back in.) Do we care about preventing any of this, or do we just say something like, "We don't recommend saving with the legacy formats, as they can become corrupted when saving larger numbers or longer lists of things than were allowed in TK3."

EDIT:
4. I'm pretty sure I'm also misusing buffer.compact(). Does that need to be in a flip/write/compact loop to do any good?

**Comment by chutchinson** [comment]
1. It's not so bad. Really there is just an empty string appended whenever legacy formats have a collection of strings because the VB code iterates (0 to n) instead of (0 to n - 1). So basically there is an extra null-byte (empty string) at the end of every sequence of strings.
2. I recommend renaming ByteBufferHelper#getBuffer to putTerminatedString for consistency with the ByteBuffer interface. To my knowledge String#getBytes(String) does not include a null character. I would also write directly to a buffer instead of wrapping the string in a buffer for writing to a channel.
3. Naturally, because we're trying to improve the technology, there are some limitations with the legacy formats we have to work around. I feel like warning users is acceptable in this case, because future users are unlikely to ever use legacy formats.
4. You don't need to use flip or compact in this case because you're only using the buffer to write. Write to the buffer, write the buffer to the channel, clear the buffer, and then repeat. Keep in mind that the buffer is fixed-length so when you're writing variable-length data you should consider checking that the buffer has enough room and acting appropriately. Compact is more appropriate when you're reading in chunks of data, process a portion of that data, but then want to read in more data without losing what's unread in the buffer.

https://kodejava.org/how-do-i-clear-a-buffer-using-compact-method/
http://tutorials.jenkov.com/java-nio/buffers.html
1. I will aim to complete the serializers I mentioned by the end of next week, possibly by the end of tomorrow (4/4/2016).

**Comment by goblinJoel** [comment]
1. I'd like to request that someone who understands the old formats look over my serializers and correct the issues with missing null bytes on sequences. It sounds fairly straightforward, but ultimately I'm not the best to say whether I'm doing it right. :P

2,4. I still need to read over your links, @chutchinson , but I'm wondering: what is the advantage of writing to the buffer instead of the channel for variable-length strings? It seems like that would just make it impossible to really know in advance (without going through all the strings again beforehand) how big to make the buffer, and if you fill up the buffer while putting the string in, don't you have to then write in the middle of that and flip it? I'm cool with doing whatever; it just sounds safer to treat each string as its own thing.

3 . Agreed.

I think after we get the serializers restored, we're ready to finally merge this one! (Then we'll need to fix the current editor branches to work with it.)

**Comment by chutchinson** [comment]
I've made significant progress, but I wasn't able to finish. I am free from work for at least this week so I think I can wrap it up in the next couple days.

@goblinJoel Actually writing directly to the channel is fairly reasonable. I forgot that ByteBuffer has **wrap** to avoid a second buffer allocation (you can wrap an existing byte array), so you can encode the string, wrap in a buffer, write to the channel, and go on your way. Ideally you would avoid a secondary buffer but it's just so much easier than trying to ensure enough space is available in an existing buffer.

That said, I recommend a putTerminatedString in ByteBufferHelper that accepts a WritableByteChannel, Charset, and a string and writes it into the channel. We might want to consider renaming that helper to something more appropriate.

**Comment by goblinJoel** [comment]
Just poking to remind @chutchinson to finish up. ;)

**Comment by goblinJoel** [comment]
Poking @chutchinson again. Meanwhile, is there anything I ought to be doing for this pull?

**Comment by chutchinson** [comment]
I decided to skip writing serialization routines because I only (personally) care about backwards compatibility in the context of running older games. I will wrap up the project serializer today and push the changes.

**Comment by goblinJoel** [comment]
So if I understand correctly, all the legacy loading code we had before this merge has been updated/moved so that it still works.

But, some of the legacy saving code is gone right now (the ones you weren't done with), while some has been updated, though they may not be bug-free (the ones I wrote).

If that's the case, I'm ok with it. Being able to read old assets is more important than being able to write them. I do still think that any we already had serialization code for should have that code updated rather than thrown away, but I wouldn't want to hold things up for that, as long as all the loading code works.

**Comment by chutchinson** [comment]
I pushed the rest of the legacy serializers (I think). 

I think we should introduce some kind of error code or preferably an enumeration to AssetException so we can avoid arbitrary strings in the asset exception for common error conditions (e.g. invalid file version, empty strings, values out of range, etc). This would be good localization and debugging.

The editor is going to need a lot of refactoring I imagine.

The project asset needs some work because it was based on the file format and not the concept. I'm going to go ahead and do some refactoring once this branch is merged.

**Comment by goblinJoel** [comment]
Sounds good. I think we can merge it. It's mostly been held up to avoid regressing on legacy serializers, and it sounds like we have most of that functionality (at least for loading) back now, albeit untested.

I'll make a todo thingy to verify that all the legacy save/loads that are still in there work, and they can be fixed later as we find issues with them.

And an error enum sounds logical to me. Not sure how this is normally handled for the localization you mention, but I can see how an enum would help keep things consistent between different serializers.

**Comment by chutchinson** [comment]
I'm going to go ahead and merge this tomorrow (Monday 5/23/2016) unless there's any complaints. I may refactor a few of the assets and then I am moving on to the engine.

**Comment by goblinJoel** [comment]
Huzzah!

**Pull request merged**
