### PR TITLE
serialization refactoring

### PR DESCRIPTION
**Pull request by chutchinson**
This PR makes a significant change to the asset management IO backend (handles, serializers) that switches from standard IO to non-blocking IO (java.nio.*). As you can imagine, it touches a couple dozen files and changes the fundamental way of constructing serializers.

Please see **net.rpgtoolkit.common.assets.serializers.legacy.LegacyAnimatedTileSerializer** for a possible legacy implementation, and **net.rpgtoolkit.common.assets.JsonSMoveSerializer** for a JSON implementation.

Some other methods were changed in name to reflect potential abberations in computational complexity. 

For example, canResolve(boolean) implies a simple boolean check; many people would imagine this is a cheap method. Documentation can resolve this, but I feel _resolvable(boolean)_ is more appropriate, as naming convention implies it's a computed value and could take some time. This is good because some serializers could perform extensive heuristics to determine if an asset can be resolved, serialized, etc. This is a common approach throughout the Java runtime library.

### CODE REVIEW

**Comment by goblinJoel** [comment]
What I was curious about on the forums was this, AbstractJsonSerializer.java: https://github.com/rpgtoolkit/core/pull/6/files#diff-1a26b9bac63f726a4a669455c59b435f . In the serialize and load methods, I had tries with multiple catches that added contextual information to the exceptions and re-threw them to be handled up the line. Now they're just tries with no catches (well, one for the load). I actually didn't even know you could do that.

I'm also curious what the benefit is to switching to ByteBuffer, CharBuffer, Charset, and having to specify an encoding are. Seems like that adds another couple things that can go wrong if the size isn't just right or there's an encoding difference. (Maybe I've been scarred by Python 2 and counterintuitive character encoding problems.)

**Comment by mariobadr** [comment]
The original code was catching any exception, which is generally a bad idea (you've basically caught any exception and reclassified it). Usually it's only a good idea to catch exceptions if you can handle them. Rethrowing exceptions with "additional" information like what was done before actually removes information that was originally there.

The try block without a catch statement is, I think, mostly for semantics. The function can throw an IO Exception or an Asset Exception. The try statement tells the programmer "I know this can throw an exception, but I can't handle it". Euix may have had a different meaning though.

**Comment by chutchinson** [comment]
Mario described my intent precisely. I hope that's sufficient along with my explanation in the development thread. The intent was to carry any IO exceptions to the call site, with an exemption for JSONException because it's contextual to the JSON serializer, so I reclassify it as an AssetException because that's precisly what it is.

Specifying encoding is necessary because the ECMAScript specification (and by extension, JSON) does not specify a character set encoding for storage or interchange. This means assuming UTF-8 or far worse, ASCII, is not a reasonable choice. 

http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf

See section 10.1 (page 116 - 117).

The code presently assumes UTF-8, but my intention was to expose the character set encoding as a key-value pair in AssetDescriptor. In fact, the reason AssetDescriptor expects a conformant URI is for something like this:
- file:///default.tst?id=10
- file:///sample.brd.json?encoding=cp1252

You can imagine the first example is a tileset, and the descriptor specifies the 11th tile. The second example specifies a board that is encoded with codepage 1252 (Windows-1252). Many text editors choose that encoding as the default.

The other reasons for NIO are essentially performance, asynchronous I/O (eventually), and because ByteBuffer provides high-performance binary serialization. The only serious problem is that ByteBuffer is static so you must be able to calculate the minimium size of the serialized asset or allocate a reasonable chunk (e.g. 4KB) and recycle the buffer occasionally.

**Comment by chutchinson** [comment]
Also, I used the try-with-resources pattern, which is why I omitted the catch blocks. They are also omitted because it avoids polluting the call stack with a rethrow.

**Comment by goblinJoel** [comment]
Any further objections to approving this? It sounds like the encoding change I objected to is pretty necessary after all, and the exception handling is better done without altering the exceptions before rethrowing. So... are we good?

**Comment by swordmaster2k** [comment]
Yeah, I'm good with this pull request. Took a look through each change will merge now.

**Pull request merged**
